models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param string $email the target email address
     * @return bool whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setFrom([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        }
        return false;
    }
}

models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 *
 * @property User|null $user This property is read-only.
 *
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;

    private $_user = false;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return bool whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        if ($this->_user === false) {
            $this->_user = User::findByUsername($this->username);
        }

        return $this->_user;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\AR;
use Yii;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\models\Form;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'dashboard', 'change-name', 'user-list'],
                'rules' => [
                    [
                        'actions' => ['logout', 'dashboard', 'change-name'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['user-list'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ]
                ],
                'denyCallback' => function () {
                    return $this->redirect(['auth']);
                },
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->redirect(['dashboard']);
    }

    public function actionAuth()
    {
        $authForm = new Form\Auth();
        $isEmailSent = false;
        if ($authForm->load(Yii::$app->request->post())) {
            $authForm->processFormSubmit();
            $isEmailSent = true;
        }
        return $this->render('auth', ['model' => $authForm, 'isEmailSent' => $isEmailSent]);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $request = Yii::$app->request;
        $email = $request->get('email');
        $token = $request->get('token');

        if ($email === null || $token === null) {
            return $this->_notFound();
        }

        if (!AR\User::isIdentityWithEmailExists($email)) {
            AR\User::createByEmail($email);
        }

        if (Yii::$app->user->loginByAccessToken($token) === null) {
            return $this->_notFound();
        };

        AR\AuthToken::deactivate($token);

        return $this->redirect(['dashboard']);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionDashboard()
    {
        $user = Yii::$app->user->getIdentity();
        return $this->render('dashboard', ['name' => $user->name]);
    }

    public function actionChangeName()
    {
        $name = Yii::$app->request->post('name');
        $userId = Yii::$app->user->getId();
        $user = AR\User::findIdentity($userId);
        $user->changeName($name);
        return $this->asJson(['success' => true]);
    }

    public function actionUserList()
    {
        $dataProvider = new ArrayDataProvider([
            'allModels' => AR\User::loadAll(),
        ]);
        return $this->render('user_list', ['dataProvider' => $dataProvider]);
    }

    private function _notFound() {
        return $this->render('error', ['name' => 'Не найдено', 'message' => 'Не найдено']);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\models\AR\User;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Тестовое задание',
        'brandUrl' => '/site/auth',
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            User::isAdmin(Yii::$app->user->getIdentity())
                ? ['label' => 'Список пользователей', 'url' => ['/site/user-list']]
                : '',
            Yii::$app->user->isGuest ? (
                ['label' => 'Войти', 'url' => ['/site/auth']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    '<span>Выйти</span> (<span class="js-navbar-user-name">' . Html::encode(Yii::$app->user->identity->name) . '</span>)',
                    ['class' => 'js-logout-button btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            ),
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/auth.php
<?php

/* @var $this yii\web\View */
/* @var $isEmailSent */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

?>

<?php if (!$isEmailSent): ?>
    <div class="js-form-container">
        <?php $form = ActiveForm::begin(['id' => 'auth-form']); ?>

            <?= $form->field($model, 'email'); ?>

            <div class="form-group">
                <?= Html::submitButton('Получить ссылку для входа', ['class' => 'js-auth-button btn btn-primary', 'name' => 'auth-button']) ?>
            </div>

        <?php ActiveForm::end(); ?>
    </div>
<?php else: ?>
    <div>Ссылка отправлена на указанную почту</div>
<?php endif; ?>

views/site/dashboard.php
<?php

/* @var $this yii\web\View */
/* @var $changeNameResponse string */

use yii\helpers\Html;
use yii\helpers\Url;

$changeNameUrl = Url::to(['/site/change-name']);
?>

<div class="js-user-name-container form-group">
    <span>Ваше имя:</span>
    <input type="text" name="user-name" class="form-control" value="<?= Html::encode($name) ?>">
</div>

<?php

$script = <<<JS
$('.js-user-name-container input').on('change', function (a) {
    const newName = $(this).val();
   $.post('$changeNameUrl', {name: newName}, (response) => {
       if (!response.success) {
           alert('Произошла ошибка');
           return;
       }
       $('.js-navbar-user-name').text(newName);
   });
});
JS;

$this->registerJs($script);

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/user_list.php
<?php

/* @var $dataProvider ArrayDataProvider */

use yii\data\ArrayDataProvider;
use yii\grid\GridView;

echo GridView::widget([
    'dataProvider' => $dataProvider,
]);